### ISSUE TITLE
Eval LTL spec?

### ISSUE THREAD

**Issue by jaysnanavati** [LouvainVerificationLab/pynusmv#2]
Hi - I can only find eval_ctl_spec, how does one evaluate an LTL spec? thanks

**Comment by sbusard** [comment]
Hello,

I see you closed the issue. Nevertheless, what follows may help you.

`eval_ctl_spec` returns the BDD corresponding to the states of the FSM that satisfy the given specification. This function is available because, when checking a CTL formula, NuSMV computes the states satisfying the specification.

For LTL specifications, NuSMV works in a different way and does not compute the states satisfying the specification. NuSMV does not rely on a corresponding `eval_ctl_spec` functionality, so PyNuSMV cannot provide one.
